import * as React from "react";
import { styled } from "@mui/material/styles";

interface ProgressBarProps {
    value: number;
}

const Root = styled("div")(({ theme }) => ({
    border: `1px solid ${theme.palette.divider}`,
    position: "relative",
    overflow: "hidden",
    width: "100%",
    height: 26,
    borderRadius: 2,
}));

const Value = styled("div")({
    position: "absolute",
    lineHeight: "24px",
    width: "100%",
    display: "flex",
    justifyContent: "center",
});

const Bar = styled("div")({
    height: "100%",
    "&.low": {
        backgroundColor: "#f44336",
    },
    "&.medium": {
        backgroundColor: "#efbb5aa3",
    },
    "&.high": {
        backgroundColor: "#088208a3",
    },
});

const ProgressBar = React.memo(function ProgressBar(props: ProgressBarProps) {
    const { value } = props;
    const valueInPercent = value * 100;

    return (
        <Root>
            <Value>{`${valueInPercent.toLocaleString()} %`}</Value>
            <Bar className={valueInPercent < 30 ? "low" : valueInPercent >= 30 && valueInPercent <= 70 ? "medium" : "high"} style={{ maxWidth: `${valueInPercent}%` }} />
        </Root>
    );
});

export function renderProgress(params: any) {
    if (params.rowNode.isAutoGenerated || params.value == null) {
        return "";
    }

    return <ProgressBar value={params.value} />;
}
